### ISSUE TITLE
Anim Preview exception, Failed to construct ImageData. The input data length is not a multiple of 4

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#1005]
Forum https://forum.playcanvas.com/t/animations-suddenly-will-not-play-in-the-editor/30251

<img width="340" alt="image" src="https://user-images.githubusercontent.com/16639049/227256343-21a108ab-ab93-4a2b-9721-db91a63f199e.png">

Looking at the code:

```
                // render to canvas
                const ctx = this._canvas.dom.getContext("2d");
                ctx.putImageData(
                    new ImageData(this._renderTarget.pixelsClamped, width, height),
                    (this._canvas.width * this._canvas.pixelRatio - width) / 2,
                    (this._canvas.height * this._canvas.pixelRatio - height) / 2
                );
```

I assume it's here

**Comment by hxmsuper** [comment]
If this error occurs during the preview of the character placed in the scene, running the project in the browser results in the following bug and the project cannot be started.

viewport-error-console.js:159  TypeError: Cannot read properties of undefined (reading 'length')
    at Skeleton.addTime (playcanvas-1.68.1.js:35178:35)
    at Skeleton.set (playcanvas-1.68.1.js:35287:10)
    at Skeleton.set (playcanvas-1.68.1.js:35272:22)
    at AnimationComponent.play (playcanvas-1.68.1.js:42671:31)
    at AnimationComponent.setModel (playcanvas-1.68.1.js:42700:11)
    at ModelComponent.set (playcanvas-1.68.1.js:53950:55)
    at ModelComponent._onModelAssetLoad (playcanvas-1.68.1.js:53804:15)
    at ModelComponent._bindModelAsset (playcanvas-1.68.1.js:53785:10)
    at ModelComponent.set (playcanvas-1.68.1.js:53908:13)
    at ModelComponentSystem.initializeComponentData (playcanvas-1.68.1.js:54201:31)

**Comment by kirelisaurimas** [comment]
I wanted to inform that this behavior is still happening. 

![image](https://github.com/user-attachments/assets/6d23fff9-1490-4c37-8e19-76e89c7c14f9)

With this warning animation preview does not work on chrome.  It does not work on all projects and only on my PC.

Restarting chrome, updating chrome, restarting pc did not make any changes.

**Comment by kirelisaurimas** [comment]
https://playcanvas.com/project/1243236/overview/animation-viewer-bug

Created new project with animation that broke everything. I was importing quite a lot, maybe that have effect?

**Comment by willeastcott** [comment]
Cannot reproduce. Closing.

If anyone can present reliable steps to reproduce the issue, please let me know and I will revisit this.

**Comment by mvaligursky** [comment]
We should not close this, I've seen this happen, it's an issue we need to investigate and fix at some point.
With the attached example, I see this:

<img width="1906" height="1299" alt="Image" src="https://github.com/user-attachments/assets/44be94fd-d7a3-450d-bedc-7e10228ffa78" />
