### ISSUE TITLE
Clicking on the transform buttons or using hotkeys in the Editor do not work

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#1025]
Try to click on any of the transform buttons on the left, they all don't work and give the error

https://github.com/playcanvas/editor/assets/16639049/f06990b7-6920-421a-9b85-73d55d8a56be

```
TypeError: Cannot read properties of undefined (reading 'op')
    at qe.<anonymous> (toolbar-gizmos.js:38:41)
    at qe.emit (index.mjs:78:21)
    at qe._onClick (index.mjs:186:18)
    at qe._onClick (index.mjs:35:15)
    at HTMLButtonElement.sentryWrapped (helpers.ts:87:17)
```

**Comment by willeastcott** [comment]
Fixed.
