### ISSUE TITLE
Anim State Graph Editor - Deleting a state when you have a transition to it gives a warning

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#769]
1. Create a state
2. Create transition to the state
3. Delete that state

Devtools has the following error:
```
instrument.ts:129 TypeError: Cannot read properties of null (reading 'id')
    at editor.js:81236:47
    at Array.forEach (<anonymous>)
    at AnimstategraphState._loadTransitions (editor.js:81234:16)
    at Observer.<anonymous> (editor.js:81355:26)
    at Observer.Events.emit (observer.js:107:31)
    at Observer.set (observer.js:657:21)
    at Observer.set (observer.js:609:33)
    at AnimstategraphView._onDeleteNode (editor.js:80061:29)
    at HTMLDivElement.<anonymous> (pcui-graph.js:8:19518)
    at HTMLDivElement.sentryWrapped (helpers.ts:87:17)
    at $h._dispatchEvent (pcui-graph.js:8:19561)
    at Object.t.action.E.DELETE_NODE.t.onClick (pcui-graph.js:8:16560)
    at Container.<anonymous> (pcui-external.js:5595:34)
    at Container.Events.emit (observer.js:107:31)
    at Container._onClick (pcui-external.js:351:22)
    at HTMLDivElement.sentryWrapped (helpers.ts:87:17)
```

https://user-images.githubusercontent.com/16639049/169345569-88259e36-0c58-4ff9-b98b-dea46ef944e1.mp4

**Comment by ellthompson** [comment]
Tested in production, these steps no longer produce a warning.
