### ISSUE TITLE
Cannot create projects if Adblock/uBlock is enabled as it prevents metrics.js from loading

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#849]
We should not be dependent on metrics for core logic.

Error message:
```
angular.min.js:93 ReferenceError: metrics is not defined
    at $scope.createNewProject (app-min.js:5442:7)
    at angular.min.js:176:290
    at C.<computed> [as formSubmit] (angular.min.js:54:343)
    at $scope.submit (app-min.js:3838:27)
    at angular.min.js:176:290
    at angular.min.js:193:357
    at a.$$childScopeClass.$$childScopeClass.$eval (angular.min.js:112:353)
    at a.$$childScopeClass.$$childScopeClass.$apply (angular.min.js:113:121)
    at HTMLFormElement.<anonymous> (angular.min.js:193:339)
    at HTMLFormElement.dispatch (jquery-2.0.3.min.js:6:10006)
```

**Comment by yaustar** [comment]
We could do a couple of things:

- Bring up a warning to disable adblock if we detect an isse
- Prevent missing metrics from stop functionality 

At the moment, trying to create a new project just looks like something is wrong on our side (eg service is down) with an infinite spinning logo

**Comment by yaustar** [comment]
+1 of user report hitting this issue

**Comment by yaustar** [comment]
+1 of user report hitting this issue

**Comment by Ciberusps** [comment]
+1 started to experience same issue several days ago, randomly loading takes up to 50s, turned off adblocker and now its fine

**Comment by yaustar** [comment]
Had another report in support emails

**Comment by yak32** [comment]
fixed
