### ISSUE TITLE
Pasting specific Light Spheres from the VR Kit into another project causes Error while saving changes

### ISSUE THREAD

**Issue by ninito-ph** [playcanvas/editor#873]
1. Open the [VR Scene](https://playcanvas.com/editor/scene/1512707) in the VR Kit sample project.
2. Copy these four light spheres
<img width="258" alt="Screenshot 2022-08-26 at 16 22 01" src="https://user-images.githubusercontent.com/59635159/186938923-a4477853-53ca-444e-99a5-b20d4b5009cf.png">
3. Paste them in any other project

Resulting crash message in console:
```js
Error: invalid:exception: Invalid path for: .components.light.affectLightMapped
    at v (share.uncompressed.js:8277:13)
    at g.handleMessage (share.uncompressed.js:8205:11)
    at e.onmessage (share.uncompressed.js:8156:18)
    at _socket.onmessage (editor-api.js:1:58149)
```
<img width="1728" alt="Screenshot 2022-08-26 at 16 24 06" src="https://user-images.githubusercontent.com/59635159/186939290-2903bd5d-ed3c-4e13-8489-6244e03d60e8.png">

**Comment by willeastcott** [comment]
The fix for this is now live on production.
